### ISSUE TITLE
How change header label in index page?

### ISSUE THREAD

**Issue by jonjts** [nicovak/slash_admin#17]
Hi, how can i change the header label in the grid of the index page?

**Comment by nicovak** [comment]
Hello, can you please provide a screenshot of what you want to change ?

**Comment by jonjts** [comment]
Sure...

**Comment by jonjts** [comment]
![image](https://user-images.githubusercontent.com/3177625/46284282-905d7e00-c54d-11e8-9b9e-c711a61c4296.png)

Right there, the header in grid.
I changed the attribute name in my pt-BR.yml but not worked.

**Comment by nicovak** [comment]
It should use your translations, internally It calls `YourModel.human_attribute_name(:attr)`
Can you try It in a `rails console` or be sure that the locale is set correctly ?
For `Actions` you must override this translation: `<%= t('slash_admin.view.actions') %>`
